use super::{CardFields, ColumnTier, ReceiptRow, account_matches, product_matches};
use crate::support::list_search::support::ColumnReorderRule;
use rust_decimal::Decimal;

pub(super) struct ReceiptKind {
    pub(super) label: &'static str,
    pub(super) list_path: &'static str,
    pub(super) preview_path: &'static str,
    pub(super) import_path: &'static str,
    pub(super) headers: &'static [&'static str],
    // 列幅は ch ではなく font-size 基準の em で指定する。`0` の字幅はフォントで変わるが、
    // `¥`・`/`・漢字を含む本文の幅は font-size に対して安定するため
    pub(super) column_widths: &'static [&'static str],
    pub(super) column_tiers: &'static [ColumnTier],
    pub(super) column_aligns: &'static [&'static str],
    pub(super) card_fields: CardFields,
    pub(super) summary_labels: [&'static str; 3],
    // ヘッダー集計の項目。(ラベル, 損益系なら負数で赤文字にするか)
    pub(super) header_items: [(&'static str, bool); 3],
    pub(super) empty_hint: &'static str,
    pub(super) csv_input_id: &'static str,
    pub(super) string_fields: &'static [fn(&ReceiptRow) -> &str],
    pub(super) search_amounts: &'static [fn(&ReceiptRow) -> Decimal],
    pub(super) product_category: bool,
    pub(super) account_category: bool,
    pub(super) reorder_rules: &'static [ColumnReorderRule<ReceiptRow>],
    pub(super) reorder_fixed: usize,
}

pub(super) const RECEIPT_KINDS: [ReceiptKind; 3] = [
    ReceiptKind {
        label: "配当金",
        list_path: "/api/v1/dividends",
        preview_path: "/api/v1/dividend-import-validations",
        import_path: "/api/v1/dividend-imports",
        headers: &[
            "入金日",
            "商品",
            "口座",
            "銘柄コード",
            "銘柄名",
            "単価",
            "数量",
            "配当金",
            "税額",
            "税引後",
        ],
        column_widths: &[
            "9em", "7.5em", "7.5em", "10em", "", "10em", "7em", "10em", "10em", "10em",
        ],
        column_tiers: &[
            ColumnTier::Core,
            ColumnTier::Wider,
            ColumnTier::Wider,
            ColumnTier::Wide,
            ColumnTier::Core,
            ColumnTier::Wider,
            ColumnTier::Md,
            ColumnTier::Core,
            ColumnTier::Core,
            ColumnTier::Core,
        ],
        column_aligns: &[
            "left", "left", "left", "center", "left", "right", "right", "right", "right", "right",
        ],
        card_fields: CardFields {
            name: 4,
            date: 0,
            account: 2,
        },
        summary_labels: ["配当金", "税額", "税引後"],
        header_items: [("配当金", false), ("税額", false), ("税引後", false)],
        empty_hint: "配当金明細をCSVで追加してください",
        csv_input_id: "csv-file-input-dividend",
        string_fields: &[
            ReceiptRow::code,
            ReceiptRow::name,
            ReceiptRow::account,
            ReceiptRow::product,
        ],
        search_amounts: &[
            |row| row.search_amount(0),
            |row| row.search_amount(1),
            |row| row.search_amount(2),
            |row| row.search_amount(3),
            |row| row.search_amount(4),
        ],
        product_category: true,
        account_category: true,
        reorder_rules: &[
            ColumnReorderRule {
                column_key: 1,
                matches: product_matches,
            },
            ColumnReorderRule {
                column_key: 2,
                matches: account_matches,
            },
        ],
        reorder_fixed: 1,
    },
    ReceiptKind {
        label: "国内株式",
        list_path: "/api/v1/domestic-stock-transactions",
        preview_path: "/api/v1/domestic-stock-import-validations",
        import_path: "/api/v1/domestic-stock-imports",
        headers: &[
            "約定日",
            "銘柄コード",
            "銘柄名",
            "口座",
            "数量",
            "売却単価",
            "売却額",
            "取得価額",
            "実現損益",
            "税額",
            "税引後",
        ],
        column_widths: &[
            "9em", "10em", "", "7.5em", "7em", "10em", "10em", "10em", "10em", "10em", "10em",
        ],
        column_tiers: &[
            ColumnTier::Core,
            ColumnTier::Wide,
            ColumnTier::Core,
            ColumnTier::Wider,
            ColumnTier::Wide,
            ColumnTier::Wider,
            ColumnTier::Wider,
            ColumnTier::Wider,
            ColumnTier::Core,
            ColumnTier::Core,
            ColumnTier::Core,
        ],
        column_aligns: &[
            "left", "center", "left", "left", "right", "right", "right", "right", "right", "right",
            "right",
        ],
        card_fields: CardFields {
            name: 2,
            date: 0,
            account: 3,
        },
        summary_labels: ["実現損益", "税額", "税引後"],
        header_items: [("実現損益", true), ("税額", false), ("税引後", true)],
        empty_hint: "国内株式明細をCSVで追加してください",
        csv_input_id: "csv-file-input-domesticstock",
        string_fields: &[ReceiptRow::code, ReceiptRow::name, ReceiptRow::account],
        search_amounts: &[
            |row| row.search_amount(0),
            |row| row.search_amount(1),
            |row| row.search_amount(2),
            |row| row.search_amount(3),
            |row| row.search_amount(4),
        ],
        product_category: false,
        account_category: true,
        reorder_rules: &[ColumnReorderRule {
            column_key: 3,
            matches: account_matches,
        }],
        reorder_fixed: 2,
    },
    ReceiptKind {
        label: "投資信託",
        list_path: "/api/v1/mutual-fund-transactions",
        preview_path: "/api/v1/mutual-fund-import-validations",
        import_path: "/api/v1/mutual-fund-imports",
        headers: &[
            "約定日",
            "ファンド名",
            "口座",
            "数量",
            "解約単価",
            "解約額",
            "取得価額",
            "実現損益",
            "税額",
            "税引後",
        ],
        column_widths: &[
            "9em", "", "7.5em", "7em", "10em", "10em", "10em", "10em", "10em", "10em",
        ],
        column_tiers: &[
            ColumnTier::Core,
            ColumnTier::Core,
            ColumnTier::Wider,
            ColumnTier::Wide,
            ColumnTier::Wider,
            ColumnTier::Wide,
            ColumnTier::Wider,
            ColumnTier::Core,
            ColumnTier::Core,
            ColumnTier::Core,
        ],
        column_aligns: &[
            "left", "left", "left", "right", "right", "right", "right", "right", "right", "right",
        ],
        card_fields: CardFields {
            name: 1,
            date: 0,
            account: 2,
        },
        summary_labels: ["実現損益", "税額", "税引後"],
        header_items: [("実現損益", true), ("税額", false), ("税引後", true)],
        empty_hint: "投資信託明細をCSVで追加してください",
        csv_input_id: "csv-file-input-mutualfund",
        string_fields: &[ReceiptRow::name, ReceiptRow::account],
        search_amounts: &[],
        product_category: false,
        account_category: false,
        reorder_rules: &[],
        reorder_fixed: 0,
    },
];
