name: Cache Cargo
description: Swatinem/rust-cache の pin をここに集約する

inputs:
  workspaces:
    required: true
  shared-key:
    required: false
    default: ""
  save-if:
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Cache Cargo
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2 https://github.com/Swatinem/rust-cache/releases/tag/v2.9.2
      with:
        workspaces: ${{ inputs.workspaces }}
        shared-key: ${{ inputs.shared-key }}
        save-if: ${{ inputs.save-if }}
